# Generated by Django 3.1.1 on 2020-12-01 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_remove_listing_highestbidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbsup',
            name='listing',
        ),
        migrations.AddField(
            model_name='thumbsup',
            name='review',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='thumbsup', to='shopping.review'),
            preserve_default=False,
        ),
    ]
