# Generated by Django 3.1.1 on 2020-12-01 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20201201_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbsup',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbsup', to='shopping.review'),
        ),
    ]
