# Generated by Django 3.1.1 on 2020-12-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20201201_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='isClosed',
        ),
    ]
