# Generated by Django 3.1.1 on 2020-12-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_remove_listing_isclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url2',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
