# Generated by Django 3.1.1 on 2020-12-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20201201_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
