# Generated by Django 3.1.1 on 2020-12-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20201201_0435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watch',
            new_name='Cart',
        ),
    ]
